[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "pandas>=2.3.0",
    "pytz>=2025.2",
    "requests>=2.32.3",
    "uvicorn>=0.34.3",
]
